FORMAT: 1A
HOST: http://localhost/api

# API Blueprintのサンプル
API Blueprintのサンプル

<%- include('sample/sample1.apib'); %>
<%- include('sample/sample2.apib'); %>
<%- include('sample/sample3.apib'); %>

